import { AgentMessage } from '@jarvis/shared-types';
import { StorageManager } from '@jarvis/storage-manager';
import { SafetyEngine, RiskLevel } from '@jarvis/safety-engine';
import { ToolRegistry } from '@jarvis/tool-registry';

export { TerminalExecutor } from '@jarvis/tool-registry';
export type { CommandExecutionResult } from '@jarvis/tool-registry';

export interface AgentResponse {
  reply: string;
  toolCalled?: string;
  toolResult?: any;
  error?: string;
  approvalRequired?: boolean;
  criticalConfirmRequired?: boolean;
  pendingCommand?: string;
  riskLevel?: RiskLevel;
  explanation?: string;
}

export class AgentCore {
  private storage: StorageManager;
  private safety: SafetyEngine;
  private tools: ToolRegistry;
  private conversationHistory: AgentMessage[] = [];

  constructor(storage: StorageManager, safety: SafetyEngine, tools: ToolRegistry) {
    this.storage = storage;
    this.safety = safety;
    this.tools = tools;
  }

  /**
   * Intent classification semantic parser maps text keywords to registries tools
   */
  private detectIntentAndTool(prompt: string, activePath: string): { toolName: string | null; args: Record<string, any> } {
    const p = prompt.toLowerCase();

    // 1. Storage Status
    if (p.includes('storage') || p.includes('disk') || p.includes('ssd') || p.includes('space') || p.includes('storage status')) {
      return { toolName: 'storage_status', args: {} };
    }

    // 2. Git read-only tools
    if (p.includes('git status') || p.includes('status batao') || p.includes('git status batao')) {
      return { toolName: 'git_status', args: { projectPath: activePath } };
    }
    if (p.includes('diff summary') || p.includes('diff do')) {
      return { toolName: 'git_diff_summary', args: { projectPath: activePath } };
    }
    if (p.includes('last commit') || p.includes('latest commit')) {
      return { toolName: 'git_last_commit', args: { projectPath: activePath } };
    }
    if (p.includes('log summary') || p.includes('recent logs')) {
      return { toolName: 'git_log_summary', args: { projectPath: activePath } };
    }
    if (p.includes('git branch') || p.includes('branch check')) {
      return { toolName: 'git_branch', args: { projectPath: activePath } };
    }

    // 3. Build tools (medium risk)
    if (p.includes('flutter analyze') || p.includes('analyze project')) {
      return { toolName: 'flutter_analyze', args: { projectPath: activePath } };
    }
    if (p.includes('build apk') || p.includes('flutter apk')) {
      return { toolName: 'flutter_build_apk', args: { projectPath: activePath } };
    }
    if (p.includes('build aab') || p.includes('appbundle')) {
      return { toolName: 'flutter_build_aab', args: { projectPath: activePath } };
    }
    if (p.includes('npm run build') || p.includes('npm build')) {
      return { toolName: 'npm_run_build', args: { projectPath: activePath } };
    }
    if (p.includes('npm run dev') || p.includes('npm dev')) {
      return { toolName: 'npm_run_dev', args: { projectPath: activePath } };
    }
    if (p.includes('npm install') || p.includes('package install')) {
      return { toolName: 'npm_install', args: { projectPath: activePath } };
    }

    // 4. File tools
    if (p.includes('open folder') || p.includes('folder open') || p.includes('project open') || p.includes('project open karo') || p.includes('selected project open karo')) {
      return { toolName: 'open_folder', args: { folderPath: activePath } };
    }
    if (p.includes('open file')) {
      return { toolName: 'open_file', args: { filePath: activePath } };
    }
    if (p.includes('list directory') || p.includes('directory list') || p.includes('files list')) {
      return { toolName: 'list_directory', args: { dirPath: activePath } };
    }
    if (p.includes('search file') || p.includes('find file') || p.includes('files search') || p.includes('project files search karo')) {
      return { toolName: 'search_file', args: { basePath: activePath, pattern: '\\.json$' } };
    }
    if (p.includes('read file') || p.includes('read content')) {
      return { toolName: 'read_file', args: { filePath: activePath } };
    }
    if (p.includes('create report') || p.includes('generate report')) {
      return { 
        toolName: 'create_report_file', 
        args: { fileName: 'assistant_report.txt', content: 'Auto report details generated by Jarvis Assistant.' } 
      };
    }
    if (p.includes('create temp') || p.includes('make temp')) {
      return { 
        toolName: 'create_temp_file', 
        args: { fileName: 'assistant_temp.tmp', content: 'Temporary cache contents.' } 
      };
    }

    return { toolName: null, args: {} };
  }

  /**
   * Processes a new user request in the text assistant cycle, checks safety, and delegates tool calls
   */
  public async handleUserPrompt(
    prompt: string,
    options?: {
      activeProjectPath?: string;
      bypassApprovalOverride?: boolean;
    }
  ): Promise<AgentResponse> {
    const activePath = options?.activeProjectPath || '';
    const bypassOverride = options?.bypassApprovalOverride || false;

    // 1. Secrets check first
    if (this.safety.scanForSecrets(prompt)) {
      return {
        reply: "Access denied. Prompt contains plain-text secret token or private key signatures.",
        error: "BLOCKED_INPUT: Potential plain-text secret leak detection."
      };
    }

    // 2. Add message to history
    this.conversationHistory.push({
      id: crypto.randomUUID(),
      role: 'user',
      content: prompt,
      timestamp: Date.now()
    });

    // 3. Match Intent & Tool
    const { toolName, args } = this.detectIntentAndTool(prompt, activePath);

    if (!toolName) {
      const fallbackReply = "Jarvis initialized. Prompt did not match any automated tool calling intents. Standing by.";
      this.conversationHistory.push({
        id: crypto.randomUUID(),
        role: 'assistant',
        content: fallbackReply,
        timestamp: Date.now()
      });
      return { reply: fallbackReply };
    }

    // 4. SSD Mount Rule check
    const isMounted = this.storage.isExternalDriveMounted();
    const writingTools = ['create_report_file', 'create_temp_file', 'flutter_build_apk', 'flutter_build_aab', 'npm_run_build'];
    
    if (!isMounted && writingTools.includes(toolName)) {
      const ssdWarning = "External SSD is not connected. Heavy data writes are paused. Actions like creating reports, temporary files, or compiling build bundles are paused.";
      return {
        reply: ssdWarning,
        error: "STORAGE_FAULT: External SSD not connected."
      };
    }

    // 5. Special Tool: storage_status mock check
    if (toolName === 'storage_status') {
      const statusText = isMounted 
        ? "Storage status check: External SSD is connected and healthy (~465 GB free). All logs and database tables are online."
        : "Storage status check: External SSD is disconnected. Heavy database logging is paused, and fallback mode is active.";
      return { reply: statusText, toolCalled: 'storage_status' };
    }

    // 6. Get tool definition
    const toolDef = this.tools.getTool(toolName);
    if (!toolDef) {
      return {
        reply: `Error: Inverted intent maps to unregistered tool "${toolName}".`,
        error: "TOOL_NOT_FOUND"
      };
    }

    // 7. Inject override options if bypassed
    const execArgs = { ...args };
    if (bypassOverride) {
      execArgs.bypassApprovalOverride = true;
      execArgs.requiresConfirmationOverride = true;
    }

    // 8. Execute Tool (secure execution boundaries)
    const result = await toolDef.execute(execArgs);

    // 9. Intercept Approval Requests to trigger UI Modals
    if (!result.success && result.error) {
      if (result.error.includes("APPROVAL_REQUIRED") || result.error.includes("TYPED_CONFIRMATION_REQUIRED")) {
        const cmd = toolName === 'flutter_build_apk' ? 'flutter build apk'
                  : toolName === 'flutter_build_aab' ? 'flutter build appbundle'
                  : toolName === 'npm_run_build' ? 'npm run build'
                  : toolName === 'npm_run_dev' ? 'npm run dev'
                  : toolName === 'npm_install' ? 'npm install'
                  : toolName === 'flutter_analyze' ? 'flutter analyze'
                  : toolName;

        const cmdReport = this.safety.analyzeCommand(cmd);

        return {
          reply: `Jarvis Shield triggered: Command execution requires user confirmation.`,
          toolCalled: toolName,
          error: result.error,
          approvalRequired: true,
          criticalConfirmRequired: cmdReport.riskLevel === 'critical',
          pendingCommand: cmd,
          riskLevel: cmdReport.riskLevel,
          explanation: cmdReport.explanation
        };
      }
    }

    // 10. Form assistant reply
    let replyText = "";
    if (result.success) {
      replyText = `Executed tool "${toolName}" successfully. Output:\n${result.output}`;
    } else {
      replyText = `Failed executing tool "${toolName}". Error: ${result.error}`;
    }

    this.conversationHistory.push({
      id: crypto.randomUUID(),
      role: 'assistant',
      content: replyText,
      timestamp: Date.now()
    });

    return {
      reply: replyText,
      toolCalled: toolName,
      toolResult: result
    };
  }

  public getHistory(): AgentMessage[] {
    return [...this.conversationHistory];
  }
}
