import { AgentMessage } from '@jarvis/shared-types';
import { StorageManager } from '@jarvis/storage-manager';
import { SafetyEngine, RiskLevel } from '@jarvis/safety-engine';
import { ToolRegistry } from '@jarvis/tool-registry';

export { TerminalExecutor } from '@jarvis/tool-registry';
export type { CommandExecutionResult } from '@jarvis/tool-registry';

export interface AgentResponse {
  reply: string;
  toolCalled?: string;
  toolResult?: any;
  error?: string;
  approvalRequired?: boolean;
  criticalConfirmRequired?: boolean;
  pendingCommand?: string;
  riskLevel?: RiskLevel;
  explanation?: string;
}

export class AgentCore {
  private storage: StorageManager;
  private safety: SafetyEngine;
  private tools: ToolRegistry;
  private conversationHistory: AgentMessage[] = [];

  constructor(storage: StorageManager, safety: SafetyEngine, tools: ToolRegistry) {
    this.storage = storage;
    this.safety = safety;
    this.tools = tools;
  }

  /**
   * Intent classification semantic parser maps text keywords to registries tools
   */
  private detectIntentAndTool(prompt: string, activePath: string): { toolName: string | null; args: Record<string, any> } {
    const p = prompt.toLowerCase();

    // 1. Storage Status
    if (p.includes('storage') || p.includes('disk') || p.includes('ssd') || p.includes('space') || p.includes('storage status')) {
      return { toolName: 'storage_status', args: {} };
    }

    // 1.5. Multi-Project Monitoring Status
    if (p.includes('saare projects') || p.includes('projects status') || p.includes('project_monitor_status')) {
      return {
        toolName: 'project_monitor_status',
        args: {}
      };
    }

    // 2. Git read-only tools
    if (p.includes('git status') || p.includes('status batao') || p.includes('git status batao')) {
      return { toolName: 'git_status', args: { projectPath: activePath } };
    }
    if (p.includes('diff summary') || p.includes('diff do')) {
      return { toolName: 'git_diff_summary', args: { projectPath: activePath } };
    }
    if (p.includes('last commit') || p.includes('latest commit')) {
      return { toolName: 'git_last_commit', args: { projectPath: activePath } };
    }
    if (p.includes('log summary') || p.includes('recent logs')) {
      return { toolName: 'git_log_summary', args: { projectPath: activePath } };
    }
    if (p.includes('git branch') || p.includes('branch check')) {
      return { toolName: 'git_branch', args: { projectPath: activePath } };
    }

    // 3. Build tools (medium risk)
    if (p.includes('flutter analyze') || p.includes('analyze project')) {
      return { toolName: 'flutter_analyze', args: { projectPath: activePath } };
    }
    if (p.includes('build apk') || p.includes('flutter apk')) {
      return { toolName: 'flutter_build_apk', args: { projectPath: activePath } };
    }
    if (p.includes('build aab') || p.includes('appbundle')) {
      return { toolName: 'flutter_build_aab', args: { projectPath: activePath } };
    }
    if (p.includes('npm run build') || p.includes('npm build')) {
      return { toolName: 'npm_run_build', args: { projectPath: activePath } };
    }
    if (p.includes('npm run dev') || p.includes('npm dev')) {
      return { toolName: 'npm_run_dev', args: { projectPath: activePath } };
    }
    if (p.includes('npm install') || p.includes('package install')) {
      return { toolName: 'npm_install', args: { projectPath: activePath } };
    }

    // 4. File tools
    if (p.includes('open folder') || p.includes('folder open') || p.includes('project open') || p.includes('project open karo') || p.includes('selected project open karo')) {
      return { toolName: 'open_folder', args: { folderPath: activePath } };
    }
    if (p.includes('open file')) {
      return { toolName: 'open_file', args: { filePath: activePath } };
    }
    if (p.includes('list directory') || p.includes('directory list') || p.includes('files list')) {
      return { toolName: 'list_directory', args: { dirPath: activePath } };
    }
    if (p.includes('search file') || p.includes('find file') || p.includes('files search') || p.includes('project files search karo')) {
      return { toolName: 'search_file', args: { basePath: activePath, pattern: '\\.json$' } };
    }
    if (p.includes('read file') || p.includes('read content')) {
      return { toolName: 'read_file', args: { filePath: activePath } };
    }
    if (p.includes('create report') || p.includes('generate report')) {
      return { 
        toolName: 'create_report_file', 
        args: { fileName: 'assistant_report.txt', content: 'Auto report details generated by Jarvis Assistant.' } 
      };
    }
    if (p.includes('create temp') || p.includes('make temp')) {
      return { 
        toolName: 'create_temp_file', 
        args: { fileName: 'assistant_temp.tmp', content: 'Temporary cache contents.' } 
      };
    }

    // 5. Gmail Draft Creation
    if (p.includes('email draft') || p.includes('draft karo') || p.includes('email draft karo') || p.includes('gmail_create_draft')) {
      let recipient = 'client@example.com';
      let subject = 'Status Update';
      let body = 'Hi, this is a draft from Jarvis.';

      if (p.includes('app ka testing kal complete ho jayega') || p.includes('app ka testing kal')) {
        body = 'Testing update: App testing will be completed tomorrow.';
        subject = 'App Testing Status Update';
        recipient = 'client@example.com';
      }

      return {
        toolName: 'gmail_create_draft',
        args: { recipient, subject, body }
      };
    }
    // 6. Reminders Creation
    if (p.includes('remind') || p.includes('remind karna') || p.includes('reminder_create')) {
      let message = 'App testing reminder';
      let time = '08:00 AM';

      if (p.includes('app testing remind karna') || p.includes('testing remind')) {
        message = 'App testing validation';
        time = 'Tomorrow 8:00 AM';
      }

      return {
        toolName: 'reminder_create',
        args: { message, time }
      };
    }

    // 7. Calendar Event Creation
    if (p.includes('event add') || p.includes('event create') || p.includes('calendar_create_event')) {
      let title = 'Project Review';
      let date = 'Friday 5:00 PM';
      let attendees = '';

      if (p.includes('project review event add') || p.includes('Friday ko 5 PM')) {
        title = 'Project Review Meeting';
        date = 'Friday 5:00 PM';
        if (p.includes('with attendees') || p.includes('members')) {
          attendees = 'client@example.com, manager@example.com';
        }
      }

      return {
        toolName: 'calendar_create_event',
        args: { title, date, attendees }
      };
    }

    // 8. Calendar List Today
    if (p.includes('calendar today') || p.includes('events today') || p.includes('calendar_list_today')) {
      return {
        toolName: 'calendar_list_today',
        args: {}
      };
    }
    // 9. Message Draft Creation
    if (p.includes('message draft') || p.includes('msg draft') || p.includes('message_create_draft')) {
      let recipient = 'Rahul';
      let message = 'I will call you in 30 minutes.';

      if (p.includes('Rahul ko message draft karo') || p.includes('Rahul')) {
        recipient = 'Rahul';
        message = 'main 30 minute me call karunga.';
      }

      return {
        toolName: 'message_create_draft',
        args: { recipient, message }
      };
    }

    // 10. Call Preparation
    if (p.includes('call prepare') || p.includes('call_prepare')) {
      let recipient = 'Rahul';
      if (p.includes('Rahul')) {
        recipient = 'Rahul';
      }

      return {
        toolName: 'call_prepare',
        args: { recipient }
      };
    }

    // 11. Contact Lookup Placeholder
    if (p.includes('lookup contact') || p.includes('find contact') || p.includes('contact_lookup_placeholder')) {
      let name = 'Rahul';
      if (p.includes('Rahul')) {
        name = 'Rahul';
      }

      return {
        toolName: 'contact_lookup_placeholder',
        args: { name }
      };
    }
    // 12. Firebase Console Open
    if (p.includes('firebase console') || p.includes('open firebase') || p.includes('open_firebase_console_placeholder')) {
      return {
        toolName: 'open_firebase_console_placeholder',
        args: {}
      };
    }

    // 13. Play Console Open
    if (p.includes('play console') || p.includes('open play') || p.includes('open_google_play_console_placeholder')) {
      return {
        toolName: 'open_google_play_console_placeholder',
        args: {}
      };
    }

    // 14. GitHub Repo Open
    if (p.includes('github repo') || p.includes('open github') || p.includes('open_github_repo_placeholder')) {
      return {
        toolName: 'open_github_repo_placeholder',
        args: {}
      };
    }

    // 15. Raw URL Open
    if (p.includes('open url') || p.includes('open link') || p.includes('open_url')) {
      let url = 'https://google.com';
      const match = prompt.match(/(https?:\/\/[^\s]+)/i);
      if (match) {
        url = match[1];
      }
      return {
        toolName: 'open_url',
        args: { url }
      };
    }

    // 16. Web Search Query
    if (p.includes('search web') || p.includes('web search') || p.includes('search_web_query')) {
      let query = 'Jarvis AI';
      return {
        toolName: 'search_web_query',
        args: { query }
      };
    }
    // 17. GitHub Issue Draft Creation
    if (p.includes('github issue draft') || p.includes('github issue') || p.includes('issue draft') || p.includes('github_create_issue_draft')) {
      let title = 'Bug Report';
      let body = 'A bug was reported by the user.';

      if (p.includes('current bug') || p.includes('bug')) {
        title = 'Bug: Voice transcriptionSSD error';
        body = 'Voice transcription fails when external SSD is unmounted.';
      }

      return {
        toolName: 'github_create_issue_draft',
        args: { title, body }
      };
    }

    // 18. GitHub Repo Status
    if (p.includes('github status') || p.includes('repo status') || p.includes('github_repo_status')) {
      return {
        toolName: 'github_repo_status',
        args: {}
      };
    }

    // 19. GitHub List Issues
    if (p.includes('github issues') || p.includes('list issues') || p.includes('github_list_issues')) {
      return {
        toolName: 'github_list_issues',
        args: {}
      };
    }

    // 20. GitHub PR Summary
    if (p.includes('github pr') || p.includes('pr summary') || p.includes('github_pr_summary')) {
      return {
        toolName: 'github_pr_summary',
        args: {}
      };
    }

    // 20.2. GitHub PR Draft Creation
    if (p.includes('pr draft') || p.includes('github_create_pr_draft')) {
      return {
        toolName: 'github_create_pr_draft',
        args: {
          title: 'Draft: Voice HUD modifications',
          headBranch: 'v1.2-development',
          baseBranch: 'main'
        }
      };
    }
 
    return { toolName: null, args: {} };
  }

  /**
   * Processes a new user request in the text assistant cycle, checks safety, and delegates tool calls
   */
  public async handleUserPrompt(
    prompt: string,
    options?: {
      activeProjectPath?: string;
      bypassApprovalOverride?: boolean;
    }
  ): Promise<AgentResponse> {
    const activePath = options?.activeProjectPath || '';
    const bypassOverride = options?.bypassApprovalOverride || false;

    // 1. Secrets check first
    if (this.safety.scanForSecrets(prompt)) {
      return {
        reply: "Access denied. Prompt contains plain-text secret token or private key signatures.",
        error: "BLOCKED_INPUT: Potential plain-text secret leak detection."
      };
    }

    // 2. Add message to history
    this.conversationHistory.push({
      id: crypto.randomUUID(),
      role: 'user',
      content: prompt,
      timestamp: Date.now()
    });

    // 3. Match Intent & Tool
    const { toolName, args } = this.detectIntentAndTool(prompt, activePath);

    if (!toolName) {
      const fallbackReply = "Jarvis initialized. Prompt did not match any automated tool calling intents. Standing by.";
      this.conversationHistory.push({
        id: crypto.randomUUID(),
        role: 'assistant',
        content: fallbackReply,
        timestamp: Date.now()
      });
      return { reply: fallbackReply };
    }

    // 4. SSD Mount Rule check
    const isMounted = this.storage.isExternalDriveMounted();
    const writingTools = ['create_report_file', 'create_temp_file', 'flutter_build_apk', 'flutter_build_aab', 'npm_run_build'];
    
    if (!isMounted && writingTools.includes(toolName)) {
      const ssdWarning = "External SSD is not connected. Heavy data writes are paused. Actions like creating reports, temporary files, or compiling build bundles are paused.";
      return {
        reply: ssdWarning,
        error: "STORAGE_FAULT: External SSD not connected."
      };
    }

    // 5. Special Tool: storage_status mock check
    if (toolName === 'storage_status') {
      const statusText = isMounted 
        ? "Storage status check: External SSD is connected and healthy (~465 GB free). All logs and database tables are online."
        : "Storage status check: External SSD is disconnected. Heavy database logging is paused, and fallback mode is active.";
      return { reply: statusText, toolCalled: 'storage_status' };
    }

    // 6. Get tool definition
    const toolDef = this.tools.getTool(toolName);
    if (!toolDef) {
      return {
        reply: `Error: Inverted intent maps to unregistered tool "${toolName}".`,
        error: "TOOL_NOT_FOUND"
      };
    }

    // 6.5. Universal Safety Gate Check
    const cmdReport = this.safety.analyzeCommand(toolName);
    if (cmdReport.isBlocked) {
      return {
        reply: `Access denied. Command "${toolName}" is blocked by security guidelines.`,
        error: `BLOCKED_COMMAND: Command "${toolName}" is blocked by security guidelines.`,
        toolCalled: toolName
      };
    }
    if (cmdReport.requiresApproval && !bypassOverride) {
      const approvalCode = cmdReport.riskLevel === 'critical' ? 'TYPED_CONFIRMATION_REQUIRED' : 'APPROVAL_REQUIRED';
      return {
        reply: `Jarvis Shield triggered: Command execution requires user confirmation.`,
        toolCalled: toolName,
        error: `${approvalCode}: Action requires user validation.`,
        approvalRequired: true,
        criticalConfirmRequired: cmdReport.riskLevel === 'critical',
        pendingCommand: toolName,
        riskLevel: cmdReport.riskLevel,
        explanation: cmdReport.explanation
      };
    }

    // 7. Inject override options if bypassed
    const execArgs = { ...args };
    if (bypassOverride) {
      execArgs.bypassApprovalOverride = true;
      execArgs.requiresConfirmationOverride = true;
    }

    // 8. Execute Tool (secure execution boundaries)
    const result = await toolDef.execute(execArgs);

    // 9. Intercept Approval Requests to trigger UI Modals
    if (!result.success && result.error) {
      if (result.error.includes("APPROVAL_REQUIRED") || result.error.includes("TYPED_CONFIRMATION_REQUIRED")) {
        const cmd = toolName === 'flutter_build_apk' ? 'flutter build apk'
                  : toolName === 'flutter_build_aab' ? 'flutter build appbundle'
                  : toolName === 'npm_run_build' ? 'npm run build'
                  : toolName === 'npm_run_dev' ? 'npm run dev'
                  : toolName === 'npm_install' ? 'npm install'
                  : toolName === 'flutter_analyze' ? 'flutter analyze'
                  : toolName;

        const cmdReport = this.safety.analyzeCommand(cmd);

        return {
          reply: `Jarvis Shield triggered: Command execution requires user confirmation.`,
          toolCalled: toolName,
          error: result.error,
          approvalRequired: true,
          criticalConfirmRequired: cmdReport.riskLevel === 'critical',
          pendingCommand: cmd,
          riskLevel: cmdReport.riskLevel,
          explanation: cmdReport.explanation
        };
      }
    }

    // 10. Form assistant reply
    let replyText = "";
    if (result.success) {
      replyText = `Executed tool "${toolName}" successfully. Output:\n${result.output}`;
    } else {
      replyText = `Failed executing tool "${toolName}". Error: ${result.error}`;
    }

    this.conversationHistory.push({
      id: crypto.randomUUID(),
      role: 'assistant',
      content: replyText,
      timestamp: Date.now()
    });

    return {
      reply: replyText,
      toolCalled: toolName,
      toolResult: result
    };
  }

  public getHistory(): AgentMessage[] {
    return [...this.conversationHistory];
  }
}
